---
version: "2.0"

services:
  node1:
    image: ghcr.io/terpnetwork/o-line:v0.0.9-terpnetwork-v4.2.2
    env:
      - MONIKER=private_node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - TERPNETWORK_P2P_PEX=true
      - TERPNETWORK_P2P_PRIVATE_PEER_IDS=<validatorid>
      - TERPNETWORK_P2P_UNCONDITIONAL_PEER_IDS=<validatorid>
      - TERPNETWORK_P2P_ADDR_BOOK_STRICT=false
      - STATESYNC_RPC_SERVERS=<publicnode1:26657,publicnode2:26657>
      - STATESYNC_SNAPSHOT_INTERVAL=500
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
    # params:
    #   storage:
    #     data:
    #       mount: /root/.akash
  node2:
    image: ghcr.io/terpnetwork/o-line:v0.0.9-terpnetwork-v4.2.2
    env:
      - MONIKER=private_node_2
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - TERPNETWORK_P2P_PEX=true
      - TERPNETWORK_P2P_PRIVATE_PEER_IDS=<validatorid>
      - TERPNETWORK_P2P_UNCONDITIONAL_PEER_IDS=<validatorid>
      - TERPNETWORK_P2P_ADDR_BOOK_STRICT=false
      - STATESYNC_RPC_SERVERS=<publicnode1:26657,publicnode2:26657>
      - STATESYNC_SNAPSHOT_INTERVAL=500
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
    # params:
    #   storage:
    #     data:
    #       mount: /root/.akash

profiles:
  compute:
    node1:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
    node2:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node1:
          denom: uakt
          amount: 1000
        node2:
          denom: uakt
          amount: 1000

deployment:
  node1:
    dcloud:
      profile: node1
      count: 1
  node2:
    dcloud:
      profile: node2
      count: 1
